name: TestAndBuild

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build Linux
        run: cargo build --release --verbose

      - name: Run tests
        run: cargo test --release --verbose

      - uses: actions/upload-artifact@v3
        with:
          name: melminter-mod.amd64-linux
          path: target/release/melminter-mod

  build-linux-musl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Update Apt
        run: sudo apt update

      - name: Install Musl
        run: sudo apt -y install musl musl-tools

      - name: Add Musl Target Triple
        run: rustup target add x86_64-unknown-linux-musl

      - name: Build Linux (Musl)
        run: cargo build --release --target x86_64-unknown-linux-musl --verbose

      - name: Run tests
        run: cargo test --release --target x86_64-unknown-linux-musl --verbose

      - uses: actions/upload-artifact@v3
        with:
          name: melminter-mod.amd64-linux-musl
          path: target/release/melminter-mod

  build-cross:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Cross
        run: cargo install cross

      - name: Build windows
        run: cross build --release --target x86_64-pc-windows-gnu --verbose

      - uses: actions/upload-artifact@v3
        with:
          name: melminter-mod.amd64-windows.exe
          path: target/x86_64-pc-windows-gnu/release/melminter-mod.exe

      - name: Build android
        run: cross build --release --target aarch64-linux-android --verbose

      - uses: actions/upload-artifact@v3
        with:
          name: melminter-mod.arm64-android
          path: target/aarch64-linux-android/release/melminter-mod

  build-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Build (mac)
        run: cargo build --release --verbose

      - uses: actions/upload-artifact@v3
        with:
          name: melminter-mod.amd64-mac
          path: target/release/melminter-mod

